<link rel="stylesheet" href="styles/header.css">
<link rel="stylesheet" href="styles/sidemenu.css">
<link rel="stylesheet" href="styles/sidemenu_transfrom.css">
<link rel="stylesheet" href="styles/slider_show.css">
<link rel="stylesheet" href="styles/login_form.css">
<link rel="stylesheet" href="styles/register_form.css">
<link rel="stylesheet" href="styles/main.css">
<link rel="stylesheet" href="styles/shopitems_sticks.css">
<link rel="stylesheet" href="styles/shopitems.css">
<link rel="stylesheet" href="styles/manage_users.css">
<link rel="stylesheet" href="styles/user_details.css">
<link rel="stylesheet" href="styles/product.css">
<link rel="stylesheet" href="styles/cart.css">
<link rel="stylesheet" href="styles/add_product.css">
<link rel="stylesheet" href="styles/payment.css">
<link rel="stylesheet" href="styles/order_confirmed.css">
<link rel="stylesheet" href="styles/order_detail.css">
<link rel="stylesheet" href="styles/edit_product.css">
<link rel="stylesheet" href="styles/contact.css">
<link rel="stylesheet" href="styles/style.css">
